# LootCrates Plugin Config file
# Version 0.1-Snapshot

Worlds: world

#max-spawned-time is set in minutes
Crates:
   max-amount: 5
   max-spawned-time: 0.5
   max-x-distance: 5000
   min-x-distance: -5000
   max-z-distance: 5000
   min-z-distance: -5000

mysql:
   host: localhost
   port: 3306
   database: lootcrates
   user: user
   password: pass

#Write items in caps
Items:
  One-Star:
    - 'LOG'
    - 'WOOD_AXE'
  Two-Star:
    - 'IRON_ORE'
    - 'IRON_AXE'
  Three-Star:
    - 'DIAMOND'
    - 'DIAMOND_AXE'
  Four-Star:
    - 'BEACON'
    - 'EMERALD'
  Five-Star:
    - 'NETHER_STAR'
    - 'EMERALD_BLOCK'

Messages:
  Found-Chest: "Congratulations! You found a Loot Crate, these Crates are randomly generated, you can find more of them throughout the world!"
  Break-Chest: "You cannot break this chest!"