name: ${artifactId}
version: ${version}
main: co.neweden.LootCrates.main
author: armadyl010
description: Spawns random Loot Crates in the world
website: https://neweden.co
softdepend: [LandManager]
commands:
  PlayerCrates:
    description: This will show current player chest count or specified
    usage: /<command> [player]
    permission: lootcrates.player
    permission-message: You don't have <permission>
  DeleteCrates:
    description: This will delete all current spawned chests
    usage: /<command>
    permission: lootcrates.delete
    permission-message: You don't have <permission>
  CurrentCrates:
    description: This will show all current chests spawned in the world
    usage: /<command>
    permission: lootcrates.current
    permission-message: You don't have <permission>
  RespawnCrates:
    description: This will respawn all the chests currently spawned
    usage: /<command>
    permission: lootcrates.respawn
    permission-message: You don't have <permission>
permissions:
  lootcrates.*:
    description: Gives access to all LootCrates commands
    children:
      lootcrates.player: true
      lootcrates.delete: true
      lootcrates.current: true
      lootcrates.respawn: true
  lootcrates.player:
    description: Allows to check the amount of crates a player has found
    default: not op
  lootcrates.delete:
    description: Allows you to delete all crates currently spawned
    default: op
  lootcrates.current:
    description: Allows you to know how many crates are currently spawned
    default: op
  lootcrates.respawn:
    description: Allows to respawn crates
    default: op